### teste

GET http://localhost:3003/ping
Content-Type : application/json

### criar estudante

POST http://localhost:3003/criarEstudante
Content-Type: application/json

{
    "nome": "Maria", 
    "email": "maria@labenu.com.br", 
    "data_nasc": "1992/02/25" , 
    "turma_id": "01"
}

### criar turma

POST  http://localhost:3003/criarTurma
Content-Type: application/json

{
    "nome": "Lammar", 
    "modulo": "01"
}


